dependencies {
    //General modules dependencies
    implementation project(':erp-common')
    implementation project(':erp-domain')
    implementation project(':erp-application')
    
    //SQL
	implementation 'org.postgresql:postgresql:42.7.13'
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
	
	//Mongo
	implementation 'org.springframework.boot:spring-boot-starter-data-mongodb'
	
	//Redis
	implementation 'org.springframework.boot:spring-boot-starter-data-redis'
	implementation 'org.springframework.boot:spring-boot-starter-cache'
}
